### ISSUE TITLE
I am using TaskT rpa for an automation code however, the code is working except that the screenshot part, every time it fails on screenshot step, and throw an error on a log. I have add the image with steps detail with the question

### ISSUE THREAD

**Issue by codenscript** [saucepleez/taskt#134]
Error: System.Exception: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(String filename, ImageFormat format)
   at System.Drawing.Image.Save(String filename)
   at taskt.Core.AutomationCommands.ScreenshotCommand.RunCommand(Object sender)
   at taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command)
   at taskt.Core.AutomationEngineInstance.ExecuteCommand(ScriptAction command)
   at taskt.Core.AutomationEngineInstance.ExecuteScript(String filePath)

**Comment by saucepleez** [comment]
Hi, are you sure that there is a display rendering?  Is this executing on a virtual machine?

**Comment by saucepleez** [comment]
Closing due to no response.
